"use client";
import { useState } from "react";
import { api, qs, useApi, useMutation } from "@/lib/api";
import { dateTime } from "@/lib/format";
import { Badge, Button, DataState, EmptyState, PageHeader, Pagination, Panel, SearchBox, Select, TextField, useToast } from "@/ui/kit";
import { DataTable } from "@/ui/table";

interface A { id: string; seq: string; occurredAt: string; actorName: string | null; action: string; module: string; entityType: string | null; entityId: string | null; before: unknown; after: unknown; metadata: unknown; ip: string | null }
const MODULES = ["platform", "students", "staff", "academics", "results", "admissions", "finance", "attendance", "timetable", "lessonnotes", "cbt", "examprep", "communication", "automation", "imports", "sync", "backup"];

export default function Audit() {
  const [action, setAction] = useState(""); const [module, setModule] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [page, setPage] = useState(1); const [open, setOpen] = useState<string | null>(null); const toast = useToast();
  const q = useApi<{ items: A[]; total: number; page: number; pageSize: number }>(`/audit${qs({ action, module, from, to, page })}`);
  const verify = useMutation(async () => { const r = await api.get<{ intact: boolean; checked: number; brokenAtSeq?: string }>("/audit/verify"); toast.push(r.intact ? "ok" : "bad", r.intact ? `Audit trail intact — ${r.checked.toLocaleString()} entries checked` : `Tampering detected at entry ${r.brokenAtSeq}`); });
  return (<><PageHeader title="Audit log" description="A permanent record of who did what: sign-ins, changes to students, results, money, permissions and settings. Entries can't be edited or deleted, and each is chained to the one before so tampering is detectable." actions={<Button variant="secondary" icon="shield" loading={verify.pending} onClick={() => void verify.run()}>Verify integrity</Button>} />
    <div className="mb-4 flex flex-wrap items-end gap-3"><SearchBox value={action} onChange={(v) => { setAction(v); setPage(1); }} placeholder="Action, e.g. payment or student.update" label="Filter by action" /><Select aria-label="Module" className="w-auto" value={module} onChange={(e) => { setModule(e.target.value); setPage(1); }}><option value="">All areas</option>{MODULES.map((m) => <option key={m}>{m}</option>)}</Select><TextField label="From" type="date" value={from} onChange={(e) => { setFrom(e.target.value); setPage(1); }} className="w-40" /><TextField label="To" type="date" value={to} onChange={(e) => { setTo(e.target.value); setPage(1); }} className="w-40" /></div>
    <DataState query={q}>{(d) => d.items.length === 0 ? <Panel><EmptyState title="No entries match" icon="shield" /></Panel> : (<><DataTable compact rows={d.items} rowKey={(a) => a.id} rule={(a) => (a.action.includes("denied") || a.action.includes("failed") || a.action.includes("reverse") ? "bad" : undefined)} onRowClick={(a) => setOpen(open === a.id ? null : a.id)} columns={[{ key: "t", header: "When", className: "whitespace-nowrap", cell: (a) => dateTime(a.occurredAt) }, { key: "u", header: "Who", cell: (a) => a.actorName ?? <span className="text-ink-500">System</span> }, { key: "a", header: "Action", cell: (a) => <span className="num font-bold">{a.action}</span> }, { key: "m", header: "Area", className: "hidden md:table-cell", cell: (a) => <Badge>{a.module}</Badge> }, { key: "e", header: "Record", className: "hidden lg:table-cell", cell: (a) => (a.entityType ? `${a.entityType} ${a.entityId?.slice(0, 8) ?? ""}` : "—") }, { key: "d", header: "", cell: (a) => (a.before || a.after || a.metadata ? <span className="text-brand-700 underline">{open === a.id ? "Hide" : "Details"}</span> : null) }]} />
      {open && (() => { const a = d.items.find((x) => x.id === open); return a ? <Panel title="Details" className="mt-3"><div className="grid gap-4 md:grid-cols-3">{(["before", "after", "metadata"] as const).map((k) => a[k] ? <div key={k}><p className="mb-1 font-bold">{k[0]!.toUpperCase() + k.slice(1)}</p><pre className="max-h-64 overflow-auto rounded bg-paper p-3 text-sm">{JSON.stringify(a[k], null, 2)}</pre></div> : null)}</div><p className="mt-2 text-sm text-ink-500">Entry {a.seq}{a.ip ? ` · from ${a.ip}` : ""}</p></Panel> : null; })()}
      <Pagination page={d.page} pageSize={d.pageSize} total={d.total} onPage={setPage} /></>)}</DataState></>);
}
