"use client";
import { useState } from "react";
import { api, useApi, useMutation } from "@/lib/api";
import { ago, date, dateTime } from "@/lib/format";
import { Badge, Button, DataState, Dialog, EmptyState, ErrorNote, PageHeader, Panel, Stat, StatusBadge, TabPanel, Tabs, TextField, Field, Textarea, useToast } from "@/ui/kit";
import { Can } from "@/ui/session";
import { DataTable } from "@/ui/table";

interface St { overview: { registered: boolean; registeredAt: string | null; pending: number; inFlight: number; failed: number; dead: number; conflict: number; acked: number; oldestPendingAgeSec: number | null; lastSyncAt: string | null; openConflicts: number }; license: { status: string; mode: string; plan: string; expiresAt: string | null; graceEndsAt: string | null; message: string | null; modules: string[] }; installation: { installationCode: string; cloudUrl: string | null; registeredAt: string | null; appVersion: string } }
interface Conf { id: string; entityType: string; entityId: string; localVersion: number; cloudVersion: number; localPayload: Record<string, unknown>; cloudPayload: Record<string, unknown>; createdAt: string }
interface Health { workers: { name: string; lastBeatAt: string; status: string }[]; events: { pending: number; parked: number }; jobs: { queue: string; status: string; count: number }[] }
type Tab = "status" | "conflicts" | "health";

export default function CloudAndLicence() {
  const q = useApi<St>("/sync/status"); const [tab, setTab] = useState<Tab>("status");
  return (<><PageHeader title="Cloud and licence" description="Your school runs on its own server. The cloud is optional: it receives a summary of selected records, checks your licence and helps with support — and never stops normal school work if it is unreachable." />
    <Tabs label="Cloud" value={tab} onChange={setTab} tabs={[{ id: "status", label: "Status" }, { id: "conflicts", label: "Conflicts", badge: q.data && q.data.overview.openConflicts > 0 ? <Badge tone="bad">{q.data.overview.openConflicts}</Badge> : undefined }, { id: "health", label: "System health" }]} />
    <TabPanel id="status" active={tab === "status"}><DataState query={q}>{(s) => <Status s={s} reload={q.reload} />}</DataState></TabPanel>
    <TabPanel id="conflicts" active={tab === "conflicts"}><Conflicts /></TabPanel><TabPanel id="health" active={tab === "health"}><HealthTab /></TabPanel></>);
}

function Status({ s, reload }: { s: St; reload: () => void }) {
  const toast = useToast(); const [dlg, setDlg] = useState(false); const [f, setF] = useState({ cloudUrl: "", registrationToken: "" });
  const reg = useMutation(async () => { const r = await api.post<{ installationCode: string }>("/sync/register", f); toast.push("ok", `Registered as ${r.installationCode}`); setDlg(false); reload(); });
  const now = useMutation(async () => { const r = await api.post<{ push: { sent: number; acked: number; failedNetwork: boolean }; heartbeat: { ok: boolean; reason?: string } }>("/sync/now"); toast.push(r.heartbeat.ok ? "ok" : "info", r.heartbeat.ok ? `Synced ${r.push.acked} record(s)` : `Cloud not reachable (${r.heartbeat.reason ?? "offline"}) — nothing is lost, it will retry automatically`); reload(); });
  const o = s.overview; const l = s.license;
  return (<div className="space-y-6">
    <Panel title="Licence"><div className="grid gap-4 sm:grid-cols-4"><div><p className="text-ink-500">Status</p><StatusBadge status={l.status} /></div><div><p className="text-ink-500">Plan</p><p className="font-bold">{l.plan}</p></div><div><p className="text-ink-500">Expires</p><p className="font-bold">{date(l.expiresAt)}</p></div><div><p className="text-ink-500">Mode</p><p className="font-bold">{l.mode === "FULL" ? "Full access" : l.mode === "READ_ONLY" ? "Read-only" : "Administrators only"}</p></div></div>{l.message && <p className="mt-3 rounded bg-amber-100 p-3 text-amber-700">{l.message}</p>}<p className="mt-3 text-sm text-ink-500">If a licence lapses the school keeps full access for a grace period, then records become read-only — your data is always yours to view, export and back up.</p></Panel>
    <Panel title="Cloud connection" actions={o.registered ? <Can perm={["sync.view"]}><Button size="sm" variant="secondary" icon="refresh" loading={now.pending} onClick={() => void now.run()}>Sync now</Button></Can> : null}>
      {!o.registered ? <div className="space-y-3"><p className="text-ink-700">This installation isn't registered with the cloud. It works completely on its own. To enable licence updates, cloud backup copies and remote support, ask your SmartSchool contact for a registration token.</p><Can perm={["settings.edit"]}><Button icon="cloud" onClick={() => setDlg(true)}>Register with the cloud</Button></Can></div> : (
        <><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat label="Waiting to send" value={o.pending + o.inFlight} note={o.oldestPendingAgeSec ? `oldest ${Math.round(o.oldestPendingAgeSec / 60)} min` : undefined} tone={o.pending > 200 ? "warn" : undefined} /><Stat label="Failing, will retry" value={o.failed} tone={o.failed ? "warn" : "ok"} /><Stat label="Needs attention" value={o.dead + o.openConflicts} tone={o.dead + o.openConflicts ? "bad" : "ok"} /><Stat label="Last successful sync" value={o.lastSyncAt ? ago(o.lastSyncAt) : "Never"} /></div><p className="mt-3 text-sm text-ink-500">Installation <strong className="num">{s.installation.installationCode}</strong> · version {s.installation.appVersion} · {s.installation.cloudUrl}</p></>)}
      <ErrorNote error={now.error} /></Panel>
    <Dialog open={dlg} onClose={() => setDlg(false)} title="Register with the cloud" footer={<><Button variant="secondary" onClick={() => setDlg(false)}>Cancel</Button><Button loading={reg.pending} disabled={!f.cloudUrl || f.registrationToken.length < 10} onClick={() => void reg.run()}>Register</Button></>}><div className="space-y-4"><TextField label="Cloud address" value={f.cloudUrl} onChange={(e) => setF({ ...f, cloudUrl: e.target.value })} placeholder="https://cloud.smartschool.ng" /><TextField label="Registration token" value={f.registrationToken} onChange={(e) => setF({ ...f, registrationToken: e.target.value })} hint="One-time token from your SmartSchool contact. This needs the internet, once." /><ErrorNote error={reg.error} /></div></Dialog>
  </div>);
}

function Conflicts() {
  const q = useApi<Conf[]>("/sync/conflicts"); const toast = useToast(); const [sel, setSel] = useState<Conf | null>(null); const [note, setNote] = useState("");
  const resolve = useMutation(async (strategy: string) => { await api.post(`/sync/conflicts/${sel!.id}/resolve`, { strategy, note: note || undefined }); toast.push("ok", "Conflict resolved"); setSel(null); setNote(""); q.reload(); });
  return (<><DataState query={q}>{(d) => d.length === 0 ? <Panel><EmptyState title="No conflicts" icon="check">Conflicts appear when the cloud holds different data for the same record — for example after restoring an old backup. Nothing is ever overwritten silently.</EmptyState></Panel> : <DataTable rows={d} rowKey={(c) => c.id} rule={() => "bad"} onRowClick={setSel} columns={[{ key: "t", header: "Record", cell: (c) => `${c.entityType.replace(/_/g, " ")}` }, { key: "l", header: "Here", align: "right", cell: (c) => `v${c.localVersion}` }, { key: "c", header: "Cloud", align: "right", cell: (c) => `v${c.cloudVersion}` }, { key: "w", header: "Found", cell: (c) => dateTime(c.createdAt) }, { key: "x", header: "", cell: () => <span className="font-bold text-brand-700">Resolve</span> }]} />}</DataState>
    <Dialog open={!!sel} onClose={() => setSel(null)} wide title="Resolve conflict" footer={<><Button variant="secondary" onClick={() => setSel(null)}>Cancel</Button><Can perm={["sync.resolve_conflicts"]}><Button variant="secondary" loading={resolve.pending} onClick={() => void resolve.run("MANUAL_RESOLVED")}>I've corrected it by hand</Button><Button loading={resolve.pending} onClick={() => void resolve.run("KEEP_LOCAL")}>Keep this school's version</Button></Can></>}>
      {sel && <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><div><p className="mb-1 font-bold">This school (v{sel.localVersion})</p><pre className="overflow-x-auto rounded bg-paper p-3 text-sm">{JSON.stringify(sel.localPayload, null, 2)}</pre></div><div><p className="mb-1 font-bold">Cloud copy (v{sel.cloudVersion})</p><pre className="overflow-x-auto rounded bg-paper p-3 text-sm">{JSON.stringify(sel.cloudPayload, null, 2)}</pre></div></div><p className="text-ink-700">This school's records are the authoritative copy. Choosing “Keep” re-sends this version as the newest. Money, results, attendance and student records are never overwritten from the cloud.</p><Field label="Note (recorded in the audit log)" htmlFor="cn"><Textarea id="cn" value={note} onChange={(e) => setNote(e.target.value)} /></Field><ErrorNote error={resolve.error} /></div>}</Dialog></>);
}

function HealthTab() {
  const q = useApi<Health>("/system/health");
  return <DataState query={q}>{(h) => (<div className="grid gap-6 lg:grid-cols-2"><Panel title="Background workers" padded={false}>{h.workers.length === 0 ? <p className="p-4 text-pen-700">No worker has reported. Notifications, sync, reports and backups will not run — start the worker service.</p> : <DataTable compact rows={h.workers} rowKey={(w) => w.name} rule={(w) => (Date.now() - new Date(w.lastBeatAt).getTime() > 300_000 || w.status !== "OK" ? "bad" : "ok")} columns={[{ key: "n", header: "Worker", cell: (w) => w.name }, { key: "s", header: "Status", cell: (w) => <StatusBadge status={w.status} /> }, { key: "b", header: "Last heartbeat", cell: (w) => ago(w.lastBeatAt) }]} />}</Panel>
    <Panel title="Queues"><ul className="space-y-1"><li>Events waiting: <strong className="num">{h.events.pending}</strong></li><li>Events that could not be processed: <strong className={`num ${h.events.parked ? "text-pen-700" : ""}`}>{h.events.parked}</strong></li>{h.jobs.filter((j) => j.status !== "SUCCEEDED").map((j) => <li key={j.queue + j.status}>{j.queue} jobs {j.status.toLowerCase()}: <strong className="num">{j.count}</strong></li>)}</ul></Panel></div>)}</DataState>;
}
