"use client";
import { use, useState } from "react";
import Link from "next/link";
import { api, useApi, useMutation } from "@/lib/api";
import { date, dateTime, money } from "@/lib/format";
import { Badge, Button, DataState, Dialog, ErrorNote, Field, PageHeader, Panel, SelectField, StatusBadge, Textarea, useToast, Checkbox } from "@/ui/kit";
import { Can } from "@/ui/session";

interface App { id: string; applicationNumber: string; status: string; version: number; firstName: string; middleName: string | null; lastName: string; gender: string; dateOfBirth: string; stateOfOrigin: string | null; lga: string | null; address: string | null; previousSchool: string | null; desiredClassId: string | null; guardianName: string; guardianRelationship: string; guardianPhone: string; guardianEmail: string | null; decisionNote: string | null; submittedAt: string | null; documents: { id: string; kind: string; fileId: string; verified: boolean; uploadedAt: string }[]; applicationFeeInvoice: { number: string; status: string; total: string; amountPaid: string } | null; student: { id: string; admissionNumber: string } | null }
const DOC: Record<string, string> = { BIRTH_CERTIFICATE: "Birth certificate", PASSPORT_PHOTO: "Passport photograph", PREVIOUS_RESULT: "Previous school result", TRANSFER_LETTER: "Transfer letter", OTHER: "Other" };

export default function AdmissionDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const q = useApi<App>(`/admissions/${id}`); const classes = useApi<{ id: string; name: string; sections: { id: string; name: string }[] }[]>("/academics/classes"); const toast = useToast();
  const [dlg, setDlg] = useState<"approve" | "reject" | "enroll" | null>(null); const [note, setNote] = useState(""); const [classId, setClassId] = useState(""); const [sectionId, setSectionId] = useState(""); const [login, setLogin] = useState(false);
  const [creds, setCreds] = useState<{ student: { admissionNumber: string }; studentLogin: { username: string; initialPassword?: string } | null; guardianLogin: { username: string; initialPassword: string } | null } | null>(null);
  const act = (path: string, body: object = {}, msg = "Done") => async () => { await api.post(`/admissions/${id}/${path}`, { version: q.data!.version, ...body }); toast.push("ok", msg); setDlg(null); q.reload(); };
  const review = useMutation(act("review", {}, "Review started")); const verified = useMutation(act("verified", {}, "Marked as verified"));
  const approve = useMutation(act("approve", { classId, note: note || undefined }, "Application approved — the guardian will be told"));
  const reject = useMutation(act("reject", { note }, "Application declined"));
  const enroll = useMutation(async () => { setCreds(await api.post(`/admissions/${id}/enroll`, { version: q.data!.version, sectionId: sectionId || null, createLogin: login })); setDlg(null); q.reload(); });
  const verify = async (docId: string, v: boolean) => { await api.post(`/admissions/documents/${docId}/verify`, { verified: v }); q.reload(); };
  return <DataState query={q}>{(a) => (<>
    <PageHeader title={`${a.firstName} ${a.lastName}`} description={`${a.applicationNumber} · submitted ${date(a.submittedAt)}`} actions={<><StatusBadge status={a.status} />
      <Can perm={["admissions.review"]}>{a.status === "SUBMITTED" && <Button loading={review.pending} onClick={() => void review.run()}>Start review</Button>}{a.status === "UNDER_REVIEW" && <Button loading={verified.pending} onClick={() => void verified.run()}>Mark verified</Button>}{["VERIFIED"].includes(a.status) && <Button onClick={() => { setClassId(a.desiredClassId ?? ""); setDlg("approve"); }}>Approve</Button>}{["SUBMITTED", "UNDER_REVIEW", "VERIFIED", "APPROVED"].includes(a.status) && <Button variant="danger" onClick={() => setDlg("reject")}>Decline</Button>}</Can>
      <Can perm={["admissions.enroll"]}>{a.status === "APPROVED" && <Button onClick={() => setDlg("enroll")}>Enrol as student</Button>}</Can></>} />
    <ErrorNote error={review.error ?? verified.error} />
    <div className="grid gap-6 lg:grid-cols-2">
      <Panel title="Applicant"><dl className="grid grid-cols-[9rem_1fr] gap-x-4 gap-y-2">{[["Sex", a.gender === "MALE" ? "Male" : "Female"], ["Date of birth", date(a.dateOfBirth)], ["State / LGA", [a.stateOfOrigin, a.lga].filter(Boolean).join(" / ") || null], ["Address", a.address], ["Previous school", a.previousSchool]].map(([k, v]) => <div key={k as string} className="contents"><dt className="text-ink-500">{k}</dt><dd>{(v as string) || "—"}</dd></div>)}</dl></Panel>
      <Panel title="Guardian"><dl className="grid grid-cols-[9rem_1fr] gap-x-4 gap-y-2"><dt className="text-ink-500">Name</dt><dd>{a.guardianName} ({a.guardianRelationship})</dd><dt className="text-ink-500">Phone</dt><dd className="num">{a.guardianPhone}</dd><dt className="text-ink-500">Email</dt><dd>{a.guardianEmail ?? "—"}</dd></dl>
        {a.applicationFeeInvoice && <p className="mt-3">Application fee <StatusBadge status={a.applicationFeeInvoice.status} /> — {money(a.applicationFeeInvoice.amountPaid)} of {money(a.applicationFeeInvoice.total)} ({a.applicationFeeInvoice.number})</p>}</Panel>
      <Panel title="Documents" className="lg:col-span-2">{a.documents.length === 0 ? <p className="text-ink-500">No documents uploaded yet.</p> : <ul className="divide-y divide-line">{a.documents.map((d) => <li key={d.id} className="flex flex-wrap items-center justify-between gap-3 py-2"><div><strong>{DOC[d.kind] ?? d.kind}</strong> <span className="text-sm text-ink-500">uploaded {dateTime(d.uploadedAt)}</span></div><div className="flex items-center gap-2"><a className="font-bold text-brand-700 underline" href={`/api/files/${d.fileId}`} target="_blank" rel="noreferrer">View</a>{d.verified ? <Badge tone="ok" icon="check">Verified</Badge> : ["UNDER_REVIEW", "VERIFIED"].includes(a.status) ? <Can perm={["admissions.review"]}><Button size="sm" variant="secondary" onClick={() => void verify(d.id, true)}>Verify</Button></Can> : <Badge tone="warn">Not verified</Badge>}</div></li>)}</ul>}</Panel>
      {a.decisionNote && <Panel title="Decision note" className="lg:col-span-2"><p>{a.decisionNote}</p></Panel>}
      {a.student && <Panel title="Student record" className="lg:col-span-2"><Link className="font-bold text-brand-700 underline" href={`/students/${a.student.id}`}>{a.student.admissionNumber}</Link></Panel>}
    </div>
    <Dialog open={dlg === "approve"} onClose={() => setDlg(null)} title="Approve application" footer={<><Button variant="secondary" onClick={() => setDlg(null)}>Cancel</Button><Button loading={approve.pending} disabled={!classId} onClick={() => void approve.run()}>Approve</Button></>}><div className="space-y-4"><SelectField label="Admit into class" value={classId} onChange={(e) => setClassId(e.target.value)} required><option value="">Choose…</option>{classes.data?.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</SelectField><Field label="Note to the family (optional)" htmlFor="an"><Textarea id="an" value={note} onChange={(e) => setNote(e.target.value)} /></Field><ErrorNote error={approve.error} /></div></Dialog>
    <Dialog open={dlg === "reject"} onClose={() => setDlg(null)} title="Decline application" footer={<><Button variant="secondary" onClick={() => setDlg(null)}>Cancel</Button><Button variant="danger" loading={reject.pending} disabled={note.trim().length < 3} onClick={() => void reject.run()}>Decline</Button></>}><Field label="Reason (the family can see this)" htmlFor="rn" required><Textarea id="rn" value={note} onChange={(e) => setNote(e.target.value)} /></Field><div className="mt-3"><ErrorNote error={reject.error} /></div></Dialog>
    <Dialog open={dlg === "enroll"} onClose={() => setDlg(null)} title="Enrol as a student" footer={<><Button variant="secondary" onClick={() => setDlg(null)}>Cancel</Button><Button loading={enroll.pending} onClick={() => void enroll.run()}>Enrol</Button></>}><div className="space-y-4"><p className="text-ink-700">Creates the student record, links the guardian (a parent account is created) and enrols the child in the approved class.</p><SelectField label="Section" value={sectionId} onChange={(e) => setSectionId(e.target.value)}><option value="">No section</option>{classes.data?.find((c) => c.id === (q.data?.desiredClassId ?? ""))?.sections.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</SelectField><Checkbox label="Create a student login" checked={login} onChange={(e) => setLogin(e.target.checked)} /><ErrorNote error={enroll.error} /></div></Dialog>
    <Dialog open={!!creds} onClose={() => setCreds(null)} title="Student enrolled" footer={<><Button variant="secondary" icon="print" onClick={() => window.print()}>Print</Button><Button onClick={() => setCreds(null)}>Done</Button></>}>{creds && <div className="space-y-3"><p>Admission number <strong className="num">{creds.student.admissionNumber}</strong>.</p>{creds.guardianLogin && <p className="rounded border border-line bg-paper p-3"><strong>Parent login</strong><br /><span className="num">{creds.guardianLogin.username} · {creds.guardianLogin.initialPassword}</span></p>}{creds.studentLogin && <p className="rounded border border-line bg-paper p-3"><strong>Student login</strong><br /><span className="num">{creds.studentLogin.username} · {creds.studentLogin.initialPassword}</span></p>}<p className="text-sm text-ink-500">Temporary passwords are shown once and must be changed at first sign-in.</p></div>}</Dialog>
  </>)}</DataState>;
}
