"use client";
import { useState } from "react";
import { api, useApi, useMutation } from "@/lib/api";
import { date } from "@/lib/format";
import { Badge, Button, DataState, Dialog, EmptyState, ErrorNote, PageHeader, Panel, SelectField, TabPanel, Tabs, TextField, useToast } from "@/ui/kit";
import { Can } from "@/ui/session";
import { DataTable } from "@/ui/table";

interface Year { id: string; name: string; startDate: string; endDate: string; isCurrent: boolean; terms: { id: string; name: string; sequence: number; startDate: string; endDate: string; isCurrent: boolean }[] }
interface Cls { id: string; name: string; level: number; stage: string; version: number; nextClassId: string | null; sections: { id: string; name: string; capacity: number | null }[]; _count: { enrollments: number } }
interface Subj { id: string; code: string; name: string; category: string | null; isCompulsory: boolean }
type Tab = "years" | "classes" | "subjects" | "assign";
const STAGES = [["NURSERY", "Nursery"], ["PRIMARY", "Primary"], ["JUNIOR_SECONDARY", "Junior secondary"], ["SENIOR_SECONDARY", "Senior secondary"]];

export default function Academics() {
  const [tab, setTab] = useState<Tab>("years");
  return (<>
    <PageHeader title="Classes and subjects" description="The academic calendar, classes, subjects and who teaches what. Set this up once, then adjust each year." />
    <Tabs label="Academic setup" value={tab} onChange={setTab} tabs={[{ id: "years", label: "Years & terms" }, { id: "classes", label: "Classes" }, { id: "subjects", label: "Subjects" }, { id: "assign", label: "Who teaches what" }]} />
    <TabPanel id="years" active={tab === "years"}><Years /></TabPanel><TabPanel id="classes" active={tab === "classes"}><Classes /></TabPanel><TabPanel id="subjects" active={tab === "subjects"}><Subjects /></TabPanel><TabPanel id="assign" active={tab === "assign"}><Assign /></TabPanel>
  </>);
}

function Years() {
  const q = useApi<Year[]>("/academics/years"); const toast = useToast();
  const [dlg, setDlg] = useState<"year" | "term" | null>(null); const [y, setY] = useState({ name: "", startDate: "", endDate: "" }); const [t, setT] = useState({ academicYearId: "", name: "First Term", sequence: 1, startDate: "", endDate: "" });
  const addY = useMutation(async () => { await api.post("/academics/years", y); toast.push("ok", "Academic year added"); setDlg(null); q.reload(); });
  const addT = useMutation(async () => { await api.post("/academics/terms", t); toast.push("ok", "Term added"); setDlg(null); q.reload(); });
  const cur = async (id: string) => { await api.post(`/academics/terms/${id}/current`); toast.push("ok", "Current term updated"); q.reload(); };
  return (<div className="space-y-4">
    <Can perm={["academics.manage"]}><div className="flex gap-2"><Button icon="plus" onClick={() => setDlg("year")}>New academic year</Button><Button variant="secondary" icon="plus" onClick={() => { setT({ ...t, academicYearId: q.data?.[0]?.id ?? "" }); setDlg("term"); }}>New term</Button></div></Can>
    <DataState query={q}>{(d) => d.length === 0 ? <Panel><EmptyState title="No academic year yet" icon="calendar">Add the current year (for example 2025/2026), then its terms.</EmptyState></Panel> : d.map((yr) => (
      <Panel key={yr.id} title={`${yr.name}${yr.isCurrent ? "  (current)" : ""}`} padded={false}><DataTable compact rows={yr.terms} rowKey={(x) => x.id} rule={(x) => (x.isCurrent ? "ok" : undefined)} columns={[{ key: "n", header: "Term", cell: (x) => <strong>{x.name}</strong> }, { key: "d", header: "Dates", cell: (x) => `${date(x.startDate)} – ${date(x.endDate)}` }, { key: "c", header: "", cell: (x) => (x.isCurrent ? <Badge tone="ok">Current term</Badge> : <Can perm={["academics.manage"]}><Button size="sm" variant="secondary" onClick={() => void cur(x.id)}>Make current</Button></Can>) }]} /></Panel>
    ))}</DataState>
    <Dialog open={dlg === "year"} onClose={() => setDlg(null)} title="New academic year" footer={<><Button variant="secondary" onClick={() => setDlg(null)}>Cancel</Button><Button loading={addY.pending} onClick={() => void addY.run()}>Add</Button></>}><div className="space-y-4"><TextField label="Name" value={y.name} onChange={(e) => setY({ ...y, name: e.target.value })} placeholder="2025/2026" /><div className="grid gap-4 sm:grid-cols-2"><TextField label="Starts" type="date" value={y.startDate} onChange={(e) => setY({ ...y, startDate: e.target.value })} /><TextField label="Ends" type="date" value={y.endDate} onChange={(e) => setY({ ...y, endDate: e.target.value })} /></div><ErrorNote error={addY.error} /></div></Dialog>
    <Dialog open={dlg === "term"} onClose={() => setDlg(null)} title="New term" footer={<><Button variant="secondary" onClick={() => setDlg(null)}>Cancel</Button><Button loading={addT.pending} onClick={() => void addT.run()}>Add</Button></>}><div className="space-y-4"><SelectField label="Academic year" value={t.academicYearId} onChange={(e) => setT({ ...t, academicYearId: e.target.value })}>{q.data?.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</SelectField><div className="grid gap-4 sm:grid-cols-2"><TextField label="Name" value={t.name} onChange={(e) => setT({ ...t, name: e.target.value })} /><SelectField label="Order" value={t.sequence} onChange={(e) => setT({ ...t, sequence: Number(e.target.value) })}>{[1, 2, 3, 4].map((n) => <option key={n}>{n}</option>)}</SelectField></div><div className="grid gap-4 sm:grid-cols-2"><TextField label="Starts" type="date" value={t.startDate} onChange={(e) => setT({ ...t, startDate: e.target.value })} /><TextField label="Ends" type="date" value={t.endDate} onChange={(e) => setT({ ...t, endDate: e.target.value })} /></div><ErrorNote error={addT.error} /></div></Dialog>
  </div>);
}

function Classes() {
  const q = useApi<Cls[]>("/academics/classes"); const toast = useToast();
  const [dlg, setDlg] = useState<"class" | "section" | null>(null); const [c, setC] = useState({ name: "", level: 1, stage: "JUNIOR_SECONDARY", nextClassId: "" }); const [s, setS] = useState({ classId: "", name: "", capacity: "" });
  const addC = useMutation(async () => { await api.post("/academics/classes", { name: c.name, level: c.level, stage: c.stage, nextClassId: c.nextClassId || null }); toast.push("ok", "Class added"); setDlg(null); q.reload(); });
  const addS = useMutation(async () => { await api.post("/academics/sections", { classId: s.classId, name: s.name, capacity: s.capacity ? Number(s.capacity) : undefined }); toast.push("ok", "Section added"); setDlg(null); q.reload(); });
  return (<div className="space-y-4"><Can perm={["academics.manage"]}><div className="flex gap-2"><Button icon="plus" onClick={() => setDlg("class")}>New class</Button><Button variant="secondary" icon="plus" onClick={() => { setS({ classId: q.data?.[0]?.id ?? "", name: "", capacity: "" }); setDlg("section"); }}>New section</Button></div></Can>
    <DataState query={q}>{(d) => d.length === 0 ? <Panel><EmptyState title="No classes yet" icon="school">Add classes such as JSS 1 to SS 3, and link each to the next so promotion works.</EmptyState></Panel> : <DataTable rows={d} rowKey={(x) => x.id} columns={[{ key: "l", header: "Level", cell: (x) => x.level }, { key: "n", header: "Class", cell: (x) => <strong>{x.name}</strong> }, { key: "s", header: "Sections", cell: (x) => x.sections.map((z) => `${z.name}${z.capacity ? ` (${z.capacity})` : ""}`).join(", ") || "—" }, { key: "e", header: "Students", align: "right", cell: (x) => x._count.enrollments }, { key: "nx", header: "Promotes to", cell: (x) => d.find((y) => y.id === x.nextClassId)?.name ?? <span className="text-ink-500">Graduation</span> }]} />}</DataState>
    <Dialog open={dlg === "class"} onClose={() => setDlg(null)} title="New class" footer={<><Button variant="secondary" onClick={() => setDlg(null)}>Cancel</Button><Button loading={addC.pending} onClick={() => void addC.run()}>Add</Button></>}><div className="space-y-4"><TextField label="Name" value={c.name} onChange={(e) => setC({ ...c, name: e.target.value })} placeholder="JSS 1" /><div className="grid gap-4 sm:grid-cols-2"><TextField label="Level (order)" type="number" min={1} value={c.level} onChange={(e) => setC({ ...c, level: Number(e.target.value) })} /><SelectField label="Stage" value={c.stage} onChange={(e) => setC({ ...c, stage: e.target.value })}>{STAGES.map(([v, l]) => <option key={v} value={v}>{l}</option>)}</SelectField></div><SelectField label="Students move on to" value={c.nextClassId} onChange={(e) => setC({ ...c, nextClassId: e.target.value })}><option value="">Graduation (final class)</option>{q.data?.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</SelectField><ErrorNote error={addC.error} /></div></Dialog>
    <Dialog open={dlg === "section"} onClose={() => setDlg(null)} title="New section" footer={<><Button variant="secondary" onClick={() => setDlg(null)}>Cancel</Button><Button loading={addS.pending} onClick={() => void addS.run()}>Add</Button></>}><div className="space-y-4"><SelectField label="Class" value={s.classId} onChange={(e) => setS({ ...s, classId: e.target.value })}>{q.data?.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</SelectField><div className="grid gap-4 sm:grid-cols-2"><TextField label="Section name" value={s.name} onChange={(e) => setS({ ...s, name: e.target.value })} placeholder="A" /><TextField label="Capacity" type="number" value={s.capacity} onChange={(e) => setS({ ...s, capacity: e.target.value })} /></div><ErrorNote error={addS.error} /></div></Dialog></div>);
}

function Subjects() {
  const q = useApi<Subj[]>("/academics/subjects"); const toast = useToast(); const [open, setOpen] = useState(false); const [f, setF] = useState({ code: "", name: "", category: "", isCompulsory: false });
  const add = useMutation(async () => { await api.post("/academics/subjects", { ...f, category: f.category || undefined }); toast.push("ok", "Subject added"); setOpen(false); setF({ code: "", name: "", category: "", isCompulsory: false }); q.reload(); });
  return (<div className="space-y-4"><Can perm={["academics.manage"]}><Button icon="plus" onClick={() => setOpen(true)}>New subject</Button></Can>
    <DataState query={q}>{(d) => d.length === 0 ? <Panel><EmptyState title="No subjects yet" icon="book" /></Panel> : <DataTable rows={d} rowKey={(x) => x.id} columns={[{ key: "c", header: "Code", cell: (x) => <span className="num font-bold">{x.code}</span> }, { key: "n", header: "Subject", cell: (x) => x.name }, { key: "g", header: "Category", cell: (x) => x.category ?? "—" }, { key: "m", header: "", cell: (x) => (x.isCompulsory ? <Badge tone="brand">Compulsory</Badge> : null) }]} />}</DataState>
    <Dialog open={open} onClose={() => setOpen(false)} title="New subject" footer={<><Button variant="secondary" onClick={() => setOpen(false)}>Cancel</Button><Button loading={add.pending} onClick={() => void add.run()}>Add</Button></>}><div className="space-y-4"><div className="grid gap-4 sm:grid-cols-[8rem_1fr]"><TextField label="Code" value={f.code} onChange={(e) => setF({ ...f, code: e.target.value })} placeholder="MTH" /><TextField label="Name" value={f.name} onChange={(e) => setF({ ...f, name: e.target.value })} placeholder="Mathematics" /></div><TextField label="Category" value={f.category} onChange={(e) => setF({ ...f, category: e.target.value })} placeholder="Core, Science, Arts…" /><label className="flex min-h-11 items-center gap-3"><input type="checkbox" className="size-5 accent-brand-700" checked={f.isCompulsory} onChange={(e) => setF({ ...f, isCompulsory: e.target.checked })} />Every student must take this subject</label><ErrorNote error={add.error} /></div></Dialog></div>);
}

function Assign() {
  const classes = useApi<Cls[]>("/academics/classes"); const subjects = useApi<Subj[]>("/academics/subjects"); const teachers = useApi<{ items: { id: string; staffNumber: string; user: { firstName: string; lastName: string } }[] }>("/teachers?pageSize=200");
  const [classId, setClassId] = useState(""); const cid = classId || classes.data?.[0]?.id || "";
  const list = useApi<{ id: string; subject: { name: string; code: string }; section: { name: string } | null; teacher: { id: string; user: { firstName: string; lastName: string } } | null }[]>(cid ? `/academics/classes/${cid}/subjects` : null);
  const [f, setF] = useState({ subjectId: "", teacherId: "" }); const toast = useToast();
  const save = useMutation(async () => { await api.post("/academics/class-subjects", { classId: cid, subjectId: f.subjectId, teacherId: f.teacherId || null }); toast.push("ok", "Saved"); setF({ subjectId: "", teacherId: "" }); list.reload(); });
  return (<div className="space-y-4">
    <SelectField label="Class" value={cid} onChange={(e) => setClassId(e.target.value)} className="max-w-xs">{classes.data?.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</SelectField>
    <Can perm={["class_subjects.manage"]}><Panel title="Assign a subject"><div className="grid gap-3 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><SelectField label="Subject" value={f.subjectId} onChange={(e) => setF({ ...f, subjectId: e.target.value })}><option value="">Choose…</option>{subjects.data?.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</SelectField><SelectField label="Teacher" value={f.teacherId} onChange={(e) => setF({ ...f, teacherId: e.target.value })}><option value="">Not assigned yet</option>{teachers.data?.items.map((t) => <option key={t.id} value={t.id}>{t.user.firstName} {t.user.lastName}</option>)}</SelectField><Button loading={save.pending} disabled={!f.subjectId} onClick={() => void save.run()}>Save</Button></div><div className="mt-3"><ErrorNote error={save.error} /></div></Panel></Can>
    <DataState query={list}>{(d) => d.length === 0 ? <Panel><EmptyState title="No subjects assigned to this class" icon="book" /></Panel> : <DataTable rows={d} rowKey={(x) => x.id} rule={(x) => (x.teacher ? "ok" : "warn")} columns={[{ key: "s", header: "Subject", cell: (x) => <strong>{x.subject.name}</strong> }, { key: "t", header: "Teacher", cell: (x) => (x.teacher ? `${x.teacher.user.firstName} ${x.teacher.user.lastName}` : <span className="text-amber-700">Needs a teacher</span>) }]} />}</DataState></div>);
}
