/**
 * The service worker's source, versioned per build. Every deploy gets a new cache version, so the `activate` step deletes the
 * previous build's caches instead of letting old assets pile up on students' devices (they are content-hashed, so they would
 * never be reused). Served by src/app/sw.js/route.ts with revalidation headers so an updated worker is picked up promptly.
 */
export function serviceWorkerSource(build: string): string {
  return SOURCE.replace("__BUILD__", JSON.stringify(build));
}

const SOURCE = "/* SmartSchool service worker.\n * Purpose: the app shell and exam room must still load after a refresh when the Wi-Fi / school server is unreachable.\n * Rules: NEVER cache /api/* (private, per-user data lives only on the server and in the exam room's IndexedDB);\n * static build assets are cache-first; page navigations are network-first with a cached fallback. */\nconst VERSION = \"ss-\" + __BUILD__;\nconst STATIC = `${VERSION}-static`;\nconst PAGES = `${VERSION}-pages`;\n\nself.addEventListener(\"install\", (e) => {\n  e.waitUntil(caches.open(STATIC).then((c) => c.addAll([\"/offline.html\", \"/icon.svg\"])).then(() => self.skipWaiting()));\n});\n\nself.addEventListener(\"activate\", (e) => {\n  e.waitUntil(\n    caches.keys().then((keys) => Promise.all(keys.filter((k) => !k.startsWith(VERSION)).map((k) => caches.delete(k)))).then(() => self.clients.claim()),\n  );\n});\n\nconst isStatic = (url) => url.pathname.startsWith(\"/_next/static/\") || /\\.(?:woff2?|svg|png|jpg|jpeg|webp|ico)$/.test(url.pathname);\n\nself.addEventListener(\"fetch\", (e) => {\n  const req = e.request;\n  if (req.method !== \"GET\") return;\n  const url = new URL(req.url);\n  if (url.origin !== self.location.origin) return;\n  if (url.pathname.startsWith(\"/api/\")) return; // network only, never stored\n\n  if (isStatic(url)) {\n    e.respondWith(\n      caches.match(req).then((hit) => hit || fetch(req).then((res) => { if (res.ok) { const copy = res.clone(); caches.open(STATIC).then((c) => c.put(req, copy)); } return res; })),\n    );\n    return;\n  }\n\n  if (req.mode === \"navigate\") {\n    e.respondWith(\n      (async () => {\n        try {\n          const ctrl = new AbortController();\n          const t = setTimeout(() => ctrl.abort(), 4000);\n          const res = await fetch(req, { signal: ctrl.signal });\n          clearTimeout(t);\n          if (res.ok && res.type === \"basic\") { const copy = res.clone(); caches.open(PAGES).then((c) => c.put(req, copy)); }\n          return res;\n        } catch {\n          return (await caches.match(req)) || (await caches.match(\"/offline.html\")) || Response.error();\n        }\n      })(),\n    );\n  }\n});\n";
