"use client";
import { useMemo, useState } from "react";
import { api, qs, useApi, useMutation } from "@/lib/api";
import { ago } from "@/lib/format";
import { Badge, Button, Checkbox, ConfirmDialog, DataState, Dialog, EmptyState, ErrorNote, PageHeader, Pagination, Panel, SearchBox, Select, SelectField, StatusBadge, TabPanel, Tabs, TextField, useToast } from "@/ui/kit";
import { Can, useSession } from "@/ui/session";
import { DataTable } from "@/ui/table";

interface U { id: string; username: string; firstName: string; lastName: string; userType: string; status: string; isPrimaryAdmin: boolean; lastLoginAt: string | null; roles: { role: { key: string; name: string } }[] }
interface Role { id: string; key: string; name: string; description: string | null; isSystem: boolean; isProtected: boolean; userCount: number; permissions: string[] }
interface Perm { key: string; module: string; description: string | null }
type Tab = "users" | "roles";

export default function UsersAndRoles() {
  const { can } = useSession(); const [tab, setTab] = useState<Tab>("users");
  return (<><PageHeader title="Users and roles" description="Who can sign in, and what each role is allowed to do. The primary admin can never be removed or locked out." />
    <Tabs label="Access" value={tab} onChange={setTab} tabs={[{ id: "users", label: "Users" }, ...(can("roles.view") ? [{ id: "roles" as Tab, label: "Roles & permissions" }] : [])]} />
    <TabPanel id="users" active={tab === "users"}><Users /></TabPanel><TabPanel id="roles" active={tab === "roles"}><Roles /></TabPanel></>);
}

function Users() {
  const [q, setQ] = useState(""); const [type, setType] = useState(""); const [page, setPage] = useState(1); const toast = useToast();
  const list = useApi<{ items: U[]; total: number; page: number; pageSize: number }>(`/users${qs({ q, userType: type, page })}`);
  const roles = useApi<Role[]>("/roles"); const [open, setOpen] = useState(false); const [sel, setSel] = useState<U | null>(null); const [reset, setReset] = useState<U | null>(null); const [pw, setPw] = useState("");
  const [f, setF] = useState({ username: "", password: "", firstName: "", lastName: "", userType: "STAFF", roleKeys: [] as string[] });
  const add = useMutation(async () => { await api.post("/users", f); toast.push("ok", "User created — they must change the password at first sign-in"); setOpen(false); list.reload(); });
  const setStatus = async (u: U, status: string) => { await api.post(`/users/${u.id}/status`, { status }); toast.push("ok", status === "ACTIVE" ? "Account enabled" : "Account disabled and signed out"); list.reload(); };
  const doReset = useMutation(async () => { await api.post(`/users/${reset!.id}/reset-password`, { password: pw }); toast.push("ok", "Password reset"); setReset(null); setPw(""); });
  const [rk, setRk] = useState<string[]>([]);
  const saveRoles = useMutation(async () => { await api.put(`/users/${sel!.id}/roles`, { roleKeys: rk }); toast.push("ok", "Roles updated"); setSel(null); list.reload(); });
  return (<div className="space-y-4">
    <div className="flex flex-wrap items-center gap-3"><SearchBox value={q} onChange={(v) => { setQ(v); setPage(1); }} placeholder="Name or username" label="Search users" /><Select aria-label="Type" className="w-auto" value={type} onChange={(e) => { setType(e.target.value); setPage(1); }}><option value="">All types</option>{["ADMIN", "TEACHER", "STAFF", "PARENT", "STUDENT"].map((t) => <option key={t} value={t}>{t[0] + t.slice(1).toLowerCase()}</option>)}</Select><Can perm={["users.create"]}><Button icon="plus" onClick={() => setOpen(true)}>New user</Button></Can></div>
    <DataState query={list}>{(d) => d.items.length === 0 ? <Panel><EmptyState title="No users found" icon="users" /></Panel> : (<><DataTable rows={d.items} rowKey={(u) => u.id} rule={(u) => (u.status !== "ACTIVE" ? "bad" : undefined)} columns={[{ key: "n", header: "Name", cell: (u) => <><strong>{u.lastName}, {u.firstName}</strong>{u.isPrimaryAdmin && <> <Badge tone="brand" icon="shield">Primary admin</Badge></>}</> }, { key: "u", header: "Username", className: "hidden sm:table-cell", cell: (u) => <span className="num">{u.username}</span> }, { key: "t", header: "Type", className: "hidden md:table-cell", cell: (u) => u.userType.toLowerCase() }, { key: "r", header: "Roles", cell: (u) => u.roles.map((r) => r.role.name).join(", ") || "—" }, { key: "l", header: "Last sign-in", className: "hidden lg:table-cell", cell: (u) => (u.lastLoginAt ? ago(u.lastLoginAt) : "never") }, { key: "s", header: "Status", cell: (u) => <StatusBadge status={u.status} /> }, { key: "a", header: "", cell: (u) => (<Can perm={["users.edit", "users.disable", "users.reset_password"]}><div className="flex flex-wrap gap-1"><Button size="sm" variant="ghost" onClick={() => { setSel(u); setRk(u.roles.map((r) => r.role.key)); }}>Roles</Button><Button size="sm" variant="ghost" onClick={() => setReset(u)}>Reset password</Button>{!u.isPrimaryAdmin && (u.status === "ACTIVE" ? <Button size="sm" variant="ghost" onClick={() => void setStatus(u, "DISABLED")}>Disable</Button> : <Button size="sm" variant="ghost" onClick={() => void setStatus(u, "ACTIVE")}>Enable</Button>)}</div></Can>) }]} /><Pagination page={d.page} pageSize={d.pageSize} total={d.total} onPage={setPage} /></>)}</DataState>
    <Dialog open={open} onClose={() => setOpen(false)} title="New user" wide footer={<><Button variant="secondary" onClick={() => setOpen(false)}>Cancel</Button><Button loading={add.pending} onClick={() => void add.run()}>Create</Button></>}><div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><TextField label="First name" value={f.firstName} onChange={(e) => setF({ ...f, firstName: e.target.value })} /><TextField label="Last name" value={f.lastName} onChange={(e) => setF({ ...f, lastName: e.target.value })} /></div><div className="grid gap-4 sm:grid-cols-2"><TextField label="Username" value={f.username} onChange={(e) => setF({ ...f, username: e.target.value })} autoCapitalize="none" /><SelectField label="Type" value={f.userType} onChange={(e) => setF({ ...f, userType: e.target.value })}>{["ADMIN", "TEACHER", "STAFF"].map((t) => <option key={t} value={t}>{t[0] + t.slice(1).toLowerCase()}</option>)}</SelectField></div><TextField label="Temporary password" type="text" value={f.password} onChange={(e) => setF({ ...f, password: e.target.value })} hint="At least 8 characters with letters and numbers. They'll change it at first sign-in." /><fieldset><legend className="mb-2 font-bold">Roles</legend><div className="grid gap-2 sm:grid-cols-2">{roles.data?.filter((r) => !r.isProtected).map((r) => <Checkbox key={r.id} label={r.name} hint={r.description ?? undefined} checked={f.roleKeys.includes(r.key)} onChange={(e) => setF({ ...f, roleKeys: e.target.checked ? [...f.roleKeys, r.key] : f.roleKeys.filter((x) => x !== r.key) })} />)}</div></fieldset><ErrorNote error={add.error} /></div></Dialog>
    <Dialog open={!!sel} onClose={() => setSel(null)} title={`Roles for ${sel?.firstName ?? ""} ${sel?.lastName ?? ""}`} footer={<><Button variant="secondary" onClick={() => setSel(null)}>Cancel</Button><Button loading={saveRoles.pending} onClick={() => void saveRoles.run()}>Save roles</Button></>}><div className="space-y-2">{roles.data?.map((r) => <Checkbox key={r.id} label={r.name + (r.isProtected ? " (owner)" : "")} hint={r.description ?? undefined} disabled={r.isProtected} checked={rk.includes(r.key)} onChange={(e) => setRk(e.target.checked ? [...rk, r.key] : rk.filter((x) => x !== r.key))} />)}<p className="text-sm text-ink-500">You can only give roles whose permissions you hold yourself.</p><ErrorNote error={saveRoles.error} /></div></Dialog>
    <ConfirmDialog open={!!reset} onClose={() => setReset(null)} title={`Reset password for ${reset?.firstName ?? ""}?`} confirmLabel="Reset password" pending={doReset.pending} onConfirm={() => void doReset.run()} body="They will be signed out everywhere and must choose a new password at next sign-in."><div className="mt-3"><TextField label="Temporary password" value={pw} onChange={(e) => setPw(e.target.value)} /><ErrorNote error={doReset.error} /></div></ConfirmDialog>
  </div>);
}

function Roles() {
  const roles = useApi<Role[]>("/roles"); const perms = useApi<Perm[]>("/permissions"); const toast = useToast();
  const [selId, setSelId] = useState(""); const [draft, setDraft] = useState<string[] | null>(null); const [open, setOpen] = useState(false); const [nr, setNr] = useState({ key: "", name: "", description: "" });
  const role = roles.data?.find((r) => r.id === selId) ?? roles.data?.[0]; const current = draft ?? role?.permissions ?? [];
  const grouped = useMemo(() => { const g = new Map<string, Perm[]>(); for (const p of perms.data ?? []) (g.get(p.module) ?? g.set(p.module, []).get(p.module)!).push(p); return [...g.entries()]; }, [perms.data]);
  const save = useMutation(async () => { await api.put(`/roles/${role!.id}/permissions`, { permissions: current }); toast.push("ok", "Permissions saved"); setDraft(null); roles.reload(); });
  const create = useMutation(async () => { await api.post("/roles", { ...nr, description: nr.description || undefined, permissions: [] }); toast.push("ok", "Role created — now choose its permissions"); setOpen(false); roles.reload(); });
  const del = useMutation(async () => { await api.del(`/roles/${role!.id}`); toast.push("ok", "Role deleted"); setSelId(""); roles.reload(); });
  const locked = !role || role.isProtected;
  return <DataState query={roles}>{(rs) => (
    <div className="grid gap-6 lg:grid-cols-[16rem_1fr]">
      <div><ul className="space-y-1">{rs.map((r) => <li key={r.id}><button onClick={() => { setSelId(r.id); setDraft(null); }} className={`flex min-h-11 w-full cursor-pointer items-center justify-between rounded-md px-3 text-left ${r.id === role?.id ? "bg-brand-100 font-bold text-brand-800" : "hover:bg-ink-100"}`}>{r.name}<span className="num text-sm text-ink-500">{r.userCount}</span></button></li>)}</ul><Can perm={["roles.manage"]}><Button className="mt-3 w-full" variant="secondary" icon="plus" onClick={() => setOpen(true)}>New role</Button></Can></div>
      {role && <Panel title={role.name} actions={<Can perm={["roles.manage"]}>{!role.isSystem && <Button size="sm" variant="ghost" icon="trash" loading={del.pending} onClick={() => void del.run()}>Delete</Button>}<Button size="sm" loading={save.pending} disabled={locked || !draft} onClick={() => void save.run()}>Save permissions</Button></Can>}>
        {role.isProtected && <p className="mb-3 rounded bg-brand-50 p-3 text-brand-800">The primary admin role always holds every permission and cannot be edited.</p>}
        <ErrorNote error={save.error ?? del.error} />
        <div className="space-y-5">{grouped.map(([mod, ps]) => (<fieldset key={mod}><legend className="mb-1 font-serif font-semibold">{mod[0]!.toUpperCase() + mod.slice(1)}</legend><div className="grid gap-x-6 gap-y-1 sm:grid-cols-2">{ps.map((p) => <Checkbox key={p.key} label={p.description ?? p.key} hint={p.key} disabled={locked} checked={role.isProtected || current.includes(p.key)} onChange={(e) => setDraft(e.target.checked ? [...current, p.key] : current.filter((x) => x !== p.key))} />)}</div></fieldset>))}</div></Panel>}
      <Dialog open={open} onClose={() => setOpen(false)} title="New role" footer={<><Button variant="secondary" onClick={() => setOpen(false)}>Cancel</Button><Button loading={create.pending} disabled={nr.key.length < 2 || nr.name.length < 2} onClick={() => void create.run()}>Create</Button></>}><div className="space-y-4"><TextField label="Name" value={nr.name} onChange={(e) => setNr({ ...nr, name: e.target.value, key: e.target.value.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "") })} placeholder="Librarian" /><TextField label="Key" value={nr.key} onChange={(e) => setNr({ ...nr, key: e.target.value })} hint="Lowercase letters, numbers and underscores" /><TextField label="Description" value={nr.description} onChange={(e) => setNr({ ...nr, description: e.target.value })} /><ErrorNote error={create.error} /></div></Dialog>
    </div>)}</DataState>;
}
